apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "collector.fullname" . }}-nri-init
  labels:
    {{- include "collector.labels" . | nindent 4 }}
data:
  nri-init.sh: |
{{ .Files.Get "scripts/nri-init.sh" | indent 4 }}